required = ["github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger"]

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.4.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "google.golang.org/genproto"

[[constraint]]
  branch = "master"
  name = "github.com/serenize/snaker"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.10.0"

[prune]
  go-tests = true
  unused-packages = true
[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "9.0.0"

[[constraint]]
  name = "github.com/vmihailenco/msgpack"
  version = "4.0.4"

[[constraint]]
  name = "github.com/go-redis/cache"
  version = "6.4.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.15.3"
